### PR TITLE
add more mime types

### PR DESCRIPTION
**Pull request by b0r1sp**
tidy up and expand default mime type list - which is I guess far from completeness, but should cover the most common ones

### CODE REVIEW

**Comment by b0r1sp** [comment]
hmm. maybe I was too optimistic:
https://ma.ttias.be/stop-caching-static-files-in-varnish/

quite interesting point.

**Comment by andristeiner** [comment]
I fully agree with Mattias's conclusion. Therefore, i tend to remove the whole section at all. And its intended as very basic example to integrate TYPO3, i expect that one has to adapt the configuration anyway.

**Comment by b0r1sp** [comment]
Before removing the section I'd include the link in the source and/or a short info + reducing the mime types to the top 5.

**Comment by rduffner** [comment]
This assumes that varnish and the local files are really local and on the same server, right?

If I have a cache that is on a different host (usually also in a different DMZ) than the host that is serving the files, it would make more sense to cache them as close to the edge as possible, I would say?

So, I would rather keep those lines in, but comment them out with a short explanation.

**Comment by andristeiner** [comment]
There are many different, valid use cases out there for different configurations. I don't want to cover all of them in this example, but only the parts relevant to the TYPO3 extension, and i expect people using Varnish to think about their setup and the appropriate configuration by them self.

**Pull request closed without merging**
